title: Anna-Carolina Haensch
logo: img/ch.png
description: Synthetic Data | Multiple Imputation | Big Data in the Social Sciences | R Programming
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
